name:                silk
version:             0.1.0.0
github:              "sudo-rushil/silk"
license:             MIT
author:              "Rushil Mallarapu"
maintainer:          "rushil.mallarapu@gmail.com"
copyright:           "Rushil Mallarapu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sudo-rushil/silk#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- algebraic-graphs >= 0.5

library:
  source-dirs: src

executables:
  silk:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - silk

tests:
  silk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - silk
